### ISSUE TITLE
[feature request] README amendment

### ISSUE THREAD

**Issue by z-eos** [xitop/clex#1]
it'd be great to have a simple instruction how to build ... something like

1. `git clone https://github.com/xitop/clex.git`
2. `cd clex`
3. `autoreconf -fis`
4. `./configure`
5. `gmake`

**Comment by xitop** [comment]
For the time being there are short instructions in the releases section: https://github.com/xitop/clex/releases/tag/v4.7

**Comment by z-eos** [comment]
ok
